### ISSUE TITLE
RxJS or SWR Integration

### ISSUE THREAD

**Issue by scha-ch** [scha-ch/daw#23]
The project settings should be managed in a non-chaotic way, some components share properties, some are nested, some will get data from a db or from anywhere, while other data comes from local configs, so it's time.

Input:
- [RxJs with React Hooks](https://blog.logrocket.com/rxjs-react-hooks-for-state-management/)

**Acceptance Criteria**

- Let's subscribe to the settings we want to
- Think about an appropriate way and implement it
- Use hooks and keep thinks flexible

**Comment by zeitiv** [comment]
Although I'm a massive fan of RxJS and reactive programming I think it could be interesting to consider the possibility to research some simpler state management libraries.

This doesn't mean we can't continue working with rxjs.
For stuff like undo and redo maybe even ngrx could be an option? You bring ton of experience with redux I bring _some_ experience with reactive rxjs.

**Comment by zeitiv** [comment]
# NgRx undo/redo

- https://nils-mehlhorn.de/posts/angular-undo-redo-ngrx-redux/

**Comment by scha-ch** [comment]
looked 10s into it. 2 impressions:

1. looks like perfect approach fpr undo/redo and also hpw I intend to use rxjs in general thx

2. the title: "Reactive State for Angular" (ngrx website) makes me feel we have to get rid pf react and switch to angular 😅??

**Comment by zeitiv** [comment]
2. No it's just that angular has rxjs by default therefore has many tutorials for it. This article is just to get the general idea.

Although I saw many people not recommending rxjs fpr this purpose since it comes with a lot of overhead. We will see :)

**Comment by zeitiv** [comment]
Also ngrx is made for angular 😅

**Comment by zeitiv** [comment]
Alternative Option:
Move the states to the Backend. (Supabase for example) Would require internet connection. Client side statemanagement could then come as a second thought for network breakages and offline support.

**Comment by zeitiv** [comment]
https://github.com/charkour/zundo

**Comment by scha-ch** [comment]
> 2. No it's just that angular has rxjs by default therefore has many tutorials for it. This article is just to get the general idea.
> 
> 
> Although I saw many people not recommending rxjs fpr this purpose since it comes with a lot of overhead. We will see :)

Right, I've red into it meanwhile. At first glance it looks like centralized project state, but that feels like a bad practice anyway, then subjects like overhead among others appearing...

I've found this one meanwhile, which feels like doing the job:
https://github.com/Widdershin/rx-undoable

However, the whole project setting feels like a all-in-one state or probably a assembled object (to save in db as one object) that could be assembled from component states. Means every component has its own state, others can subscribe to messages and all of them can trigger an update which will update part of the object (using MongoDB, feels comfy)

Am I'm missing something? Thanks!

**Comment by scha-ch** [comment]
> 

Will look into it. Sure about internet connection?
Next.js could write the state into a file (requires to start a local server to fs.writeFileSync or there is FileAPI I suppose?
Then on 'online' sync it back to db?

**Comment by scha-ch** [comment]
> * https://github.com/charkour/zundo - Undo Redo with Zustand
> 
>     * https://zustand-rx.vercel.app/en/introduction.md Zustand and RxJs :)
> 
>     * https://github.com/Romainlg29/use-broadcast - Share State between tabs. (One tab each for pianoroll etc)

Thank you, now I got some homework to do =)
Need to make sure collaboration in same project works seamlessly, this might come with the probably acceptable consent to not edit the same track (a track belongs to one user only, feels clean anyway, but that's just the beginning of the road to think through), there are e.g. global send effect channels that are used by multiple tracks, but even there, one responsible user feels right? etc. just first thoughts)

thanks for the input, if I feel it's too much to decide right now (priority is having a useable release to produce music) I will implement the very basics and create a follow up task.

**Comment by scha-ch** [comment]
@zeitiv Using SWR for now. Seems to be the straight forward approach here. Database integration will be put into another task, we have to discuss and evaluate before deciding this, so I keep it simple here to continue with the relevant tasks to finally be able to compose music ;) thanks again! Very nice variants, we can talk about them again in the (near) future.
